### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by broxen** [claudioc/jingo-2#11]
Is this project abandoned?

I tried looking for the demo site for Jingo 1.x and it appeared to be down, but stumbled upon reference to this next version. Is this still being worked on?

There appears to only be one other Node.js based wiki engine, and with 44 open PRs, it's development appears stalled. Seems like the community may benefit from options in the space?

**Comment by claudioc** [comment]
@broxen thanks for asking! I am trying to restart development in this project, at least to bring it to a stable version 1. I hope by the end of the year to have it ready 👍🏻

**Comment by claudioc** [comment]
(development in Jingo 1 is definitely stopped since the codebase is *really* old)
